const mjtState = mjtState_
const mjtWarning = mjtWarning_
const mjtTimer = mjtTimer_
struct mjContact_
    dist::mjtNum
    pos::NTuple{3,mjtNum}
    frame::NTuple{9,mjtNum}
    includemargin::mjtNum
    friction::NTuple{5,mjtNum}
    solref::NTuple{2,mjtNum}
    solreffriction::NTuple{2,mjtNum}
    solimp::NTuple{5,mjtNum}
    mu::mjtNum
    H::NTuple{36,mjtNum}
    dim::Cint
    geom1::Cint
    geom2::Cint
    exclude::Cint
    efc_address::Cint
end
const mjContact = mjContact_
struct mjWarningStat_
    lastinfo::Cint
    number::Cint
end
const mjWarningStat = mjWarningStat_
struct mjTimerStat_
    duration::mjtNum
    number::Cint
end
const mjTimerStat = mjTimerStat_
struct mjSolverStat_
    improvement::mjtNum
    gradient::mjtNum
    lineslope::mjtNum
    nactive::Cint
    nchange::Cint
    neval::Cint
    nupdate::Cint
end
const mjSolverStat = mjSolverStat_
struct mjData_
    nstack::Cint
    nbuffer::Cint
    nplugin::Cint
    pstack::Csize_t
    parena::Csize_t
    maxuse_stack::Cint
    maxuse_arena::Csize_t
    maxuse_con::Cint
    maxuse_efc::Cint
    warning::NTuple{8,mjWarningStat}
    timer::NTuple{13,mjTimerStat}
    solver::NTuple{1000,mjSolverStat}
    solver_iter::Cint
    solver_nnz::Cint
    solver_fwdinv::NTuple{2,mjtNum}
    nbodypair_broad::Cint
    nbodypair_narrow::Cint
    ngeompair_mid::Cint
    ngeompair_narrow::Cint
    ne::Cint
    nf::Cint
    nefc::Cint
    nnzJ::Cint
    ncon::Cint
    time::mjtNum
    energy::NTuple{2,mjtNum}
    buffer::Ptr{Cvoid}
    arena::Ptr{Cvoid}
    qpos::Ptr{mjtNum}
    qvel::Ptr{mjtNum}
    act::Ptr{mjtNum}
    qacc_warmstart::Ptr{mjtNum}
    plugin_state::Ptr{mjtNum}
    ctrl::Ptr{mjtNum}
    qfrc_applied::Ptr{mjtNum}
    xfrc_applied::Ptr{mjtNum}
    mocap_pos::Ptr{mjtNum}
    mocap_quat::Ptr{mjtNum}
    qacc::Ptr{mjtNum}
    act_dot::Ptr{mjtNum}
    userdata::Ptr{mjtNum}
    sensordata::Ptr{mjtNum}
    plugin::Ptr{Cint}
    plugin_data::Ptr{Csize_t}
    xpos::Ptr{mjtNum}
    xquat::Ptr{mjtNum}
    xmat::Ptr{mjtNum}
    xipos::Ptr{mjtNum}
    ximat::Ptr{mjtNum}
    xanchor::Ptr{mjtNum}
    xaxis::Ptr{mjtNum}
    geom_xpos::Ptr{mjtNum}
    geom_xmat::Ptr{mjtNum}
    site_xpos::Ptr{mjtNum}
    site_xmat::Ptr{mjtNum}
    cam_xpos::Ptr{mjtNum}
    cam_xmat::Ptr{mjtNum}
    light_xpos::Ptr{mjtNum}
    light_xdir::Ptr{mjtNum}
    subtree_com::Ptr{mjtNum}
    cdof::Ptr{mjtNum}
    cinert::Ptr{mjtNum}
    ten_wrapadr::Ptr{Cint}
    ten_wrapnum::Ptr{Cint}
    ten_J_rownnz::Ptr{Cint}
    ten_J_rowadr::Ptr{Cint}
    ten_J_colind::Ptr{Cint}
    ten_length::Ptr{mjtNum}
    ten_J::Ptr{mjtNum}
    wrap_obj::Ptr{Cint}
    wrap_xpos::Ptr{mjtNum}
    actuator_length::Ptr{mjtNum}
    actuator_moment::Ptr{mjtNum}
    crb::Ptr{mjtNum}
    qM::Ptr{mjtNum}
    qLD::Ptr{mjtNum}
    qLDiagInv::Ptr{mjtNum}
    qLDiagSqrtInv::Ptr{mjtNum}
    bvh_active::Ptr{mjtByte}
    ten_velocity::Ptr{mjtNum}
    actuator_velocity::Ptr{mjtNum}
    cvel::Ptr{mjtNum}
    cdof_dot::Ptr{mjtNum}
    qfrc_bias::Ptr{mjtNum}
    qfrc_passive::Ptr{mjtNum}
    efc_vel::Ptr{mjtNum}
    efc_aref::Ptr{mjtNum}
    subtree_linvel::Ptr{mjtNum}
    subtree_angmom::Ptr{mjtNum}
    qH::Ptr{mjtNum}
    qHDiagInv::Ptr{mjtNum}
    D_rownnz::Ptr{Cint}
    D_rowadr::Ptr{Cint}
    D_colind::Ptr{Cint}
    B_rownnz::Ptr{Cint}
    B_rowadr::Ptr{Cint}
    B_colind::Ptr{Cint}
    qDeriv::Ptr{mjtNum}
    qLU::Ptr{mjtNum}
    actuator_force::Ptr{mjtNum}
    qfrc_actuator::Ptr{mjtNum}
    qfrc_smooth::Ptr{mjtNum}
    qacc_smooth::Ptr{mjtNum}
    qfrc_constraint::Ptr{mjtNum}
    qfrc_inverse::Ptr{mjtNum}
    cacc::Ptr{mjtNum}
    cfrc_int::Ptr{mjtNum}
    cfrc_ext::Ptr{mjtNum}
    contact::Ptr{mjContact}
    efc_type::Ptr{Cint}
    efc_id::Ptr{Cint}
    efc_J_rownnz::Ptr{Cint}
    efc_J_rowadr::Ptr{Cint}
    efc_J_rowsuper::Ptr{Cint}
    efc_J_colind::Ptr{Cint}
    efc_JT_rownnz::Ptr{Cint}
    efc_JT_rowadr::Ptr{Cint}
    efc_JT_rowsuper::Ptr{Cint}
    efc_JT_colind::Ptr{Cint}
    efc_J::Ptr{mjtNum}
    efc_JT::Ptr{mjtNum}
    efc_pos::Ptr{mjtNum}
    efc_margin::Ptr{mjtNum}
    efc_frictionloss::Ptr{mjtNum}
    efc_diagApprox::Ptr{mjtNum}
    efc_KBIP::Ptr{mjtNum}
    efc_D::Ptr{mjtNum}
    efc_R::Ptr{mjtNum}
    efc_b::Ptr{mjtNum}
    efc_force::Ptr{mjtNum}
    efc_state::Ptr{Cint}
    efc_AR_rownnz::Ptr{Cint}
    efc_AR_rowadr::Ptr{Cint}
    efc_AR_colind::Ptr{Cint}
    efc_AR::Ptr{mjtNum}
end
const mjData = mjData_
const mjtDisableBit = mjtDisableBit_
const mjtEnableBit = mjtEnableBit_
const mjtJoint = mjtJoint_
const mjtGeom = mjtGeom_
const mjtCamLight = mjtCamLight_
const mjtTexture = mjtTexture_
const mjtIntegrator = mjtIntegrator_
const mjtCollision = mjtCollision_
const mjtCone = mjtCone_
const mjtJacobian = mjtJacobian_
const mjtSolver = mjtSolver_
const mjtEq = mjtEq_
const mjtWrap = mjtWrap_
const mjtTrn = mjtTrn_
const mjtDyn = mjtDyn_
const mjtGain = mjtGain_
const mjtBias = mjtBias_
const mjtObj = mjtObj_
const mjtConstraint = mjtConstraint_
const mjtConstraintState = mjtConstraintState_
const mjtSensor = mjtSensor_
const mjtStage = mjtStage_
const mjtDataType = mjtDataType_
const mjtLRMode = mjtLRMode_
struct mjLROpt_
    mode::Cint
    useexisting::Cint
    uselimit::Cint
    accel::mjtNum
    maxforce::mjtNum
    timeconst::mjtNum
    timestep::mjtNum
    inttotal::mjtNum
    interval::mjtNum
    tolrange::mjtNum
end
const mjLROpt = mjLROpt_
struct mjVFS_
    nfile::Cint
    filename::NTuple{2000,NTuple{1000,Cchar}}
    filesize::NTuple{2000,Cint}
    filedata::NTuple{2000,Ptr{Cvoid}}
end
const mjVFS = mjVFS_
struct mjResource_
    name::Ptr{Cchar}
    data::Ptr{Cvoid}
    provider_data::Ptr{Cvoid}
    read::Ptr{Cvoid}
    close::Ptr{Cvoid}
    getdir::Ptr{Cvoid}
end
const mjResource = mjResource_
struct mjOption_
    timestep::mjtNum
    apirate::mjtNum
    impratio::mjtNum
    tolerance::mjtNum
    noslip_tolerance::mjtNum
    mpr_tolerance::mjtNum
    gravity::NTuple{3,mjtNum}
    wind::NTuple{3,mjtNum}
    magnetic::NTuple{3,mjtNum}
    density::mjtNum
    viscosity::mjtNum
    o_margin::mjtNum
    o_solref::NTuple{2,mjtNum}
    o_solimp::NTuple{5,mjtNum}
    integrator::Cint
    collision::Cint
    cone::Cint
    jacobian::Cint
    solver::Cint
    iterations::Cint
    noslip_iterations::Cint
    mpr_iterations::Cint
    disableflags::Cint
    enableflags::Cint
end
const mjOption = mjOption_
struct var"##Ctag#314"
    fovy::Cfloat
    ipd::Cfloat
    azimuth::Cfloat
    elevation::Cfloat
    linewidth::Cfloat
    glow::Cfloat
    realtime::Cfloat
    offwidth::Cint
    offheight::Cint
    ellipsoidinertia::Cint
end
struct var"##Ctag#315"
    shadowsize::Cint
    offsamples::Cint
    numslices::Cint
    numstacks::Cint
    numquads::Cint
end
struct var"##Ctag#316"
    ambient::NTuple{3,Cfloat}
    diffuse::NTuple{3,Cfloat}
    specular::NTuple{3,Cfloat}
    active::Cint
end
struct var"##Ctag#317"
    stiffness::Cfloat
    stiffnessrot::Cfloat
    force::Cfloat
    torque::Cfloat
    alpha::Cfloat
    fogstart::Cfloat
    fogend::Cfloat
    znear::Cfloat
    zfar::Cfloat
    haze::Cfloat
    shadowclip::Cfloat
    shadowscale::Cfloat
    actuatortendon::Cfloat
end
struct var"##Ctag#318"
    forcewidth::Cfloat
    contactwidth::Cfloat
    contactheight::Cfloat
    connect::Cfloat
    com::Cfloat
    camera::Cfloat
    light::Cfloat
    selectpoint::Cfloat
    jointlength::Cfloat
    jointwidth::Cfloat
    actuatorlength::Cfloat
    actuatorwidth::Cfloat
    framelength::Cfloat
    framewidth::Cfloat
    constraint::Cfloat
    slidercrank::Cfloat
end
struct var"##Ctag#319"
    fog::NTuple{4,Cfloat}
    haze::NTuple{4,Cfloat}
    force::NTuple{4,Cfloat}
    inertia::NTuple{4,Cfloat}
    joint::NTuple{4,Cfloat}
    actuator::NTuple{4,Cfloat}
    actuatornegative::NTuple{4,Cfloat}
    actuatorpositive::NTuple{4,Cfloat}
    com::NTuple{4,Cfloat}
    camera::NTuple{4,Cfloat}
    light::NTuple{4,Cfloat}
    selectpoint::NTuple{4,Cfloat}
    connect::NTuple{4,Cfloat}
    contactpoint::NTuple{4,Cfloat}
    contactforce::NTuple{4,Cfloat}
    contactfriction::NTuple{4,Cfloat}
    contacttorque::NTuple{4,Cfloat}
    contactgap::NTuple{4,Cfloat}
    rangefinder::NTuple{4,Cfloat}
    constraint::NTuple{4,Cfloat}
    slidercrank::NTuple{4,Cfloat}
    crankbroken::NTuple{4,Cfloat}
end
struct mjVisual_
    data::NTuple{568,UInt8}
end
const mjVisual = mjVisual_
struct mjStatistic_
    meaninertia::mjtNum
    meanmass::mjtNum
    meansize::mjtNum
    extent::mjtNum
    center::NTuple{3,mjtNum}
end
const mjStatistic = mjStatistic_
struct mjModel_
    nq::Cint
    nv::Cint
    nu::Cint
    na::Cint
    nbody::Cint
    nbvh::Cint
    njnt::Cint
    ngeom::Cint
    nsite::Cint
    ncam::Cint
    nlight::Cint
    nmesh::Cint
    nmeshvert::Cint
    nmeshnormal::Cint
    nmeshtexcoord::Cint
    nmeshface::Cint
    nmeshgraph::Cint
    nskin::Cint
    nskinvert::Cint
    nskintexvert::Cint
    nskinface::Cint
    nskinbone::Cint
    nskinbonevert::Cint
    nhfield::Cint
    nhfielddata::Cint
    ntex::Cint
    ntexdata::Cint
    nmat::Cint
    npair::Cint
    nexclude::Cint
    neq::Cint
    ntendon::Cint
    nwrap::Cint
    nsensor::Cint
    nnumeric::Cint
    nnumericdata::Cint
    ntext::Cint
    ntextdata::Cint
    ntuple::Cint
    ntupledata::Cint
    nkey::Cint
    nmocap::Cint
    nplugin::Cint
    npluginattr::Cint
    nuser_body::Cint
    nuser_jnt::Cint
    nuser_geom::Cint
    nuser_site::Cint
    nuser_cam::Cint
    nuser_tendon::Cint
    nuser_actuator::Cint
    nuser_sensor::Cint
    nnames::Cint
    nnames_map::Cint
    nM::Cint
    nD::Cint
    nB::Cint
    nemax::Cint
    njmax::Cint
    nconmax::Cint
    nstack::Cint
    nuserdata::Cint
    nsensordata::Cint
    npluginstate::Cint
    nbuffer::Cint
    opt::mjOption
    vis::mjVisual
    stat::mjStatistic
    buffer::Ptr{Cvoid}
    qpos0::Ptr{mjtNum}
    qpos_spring::Ptr{mjtNum}
    body_parentid::Ptr{Cint}
    body_rootid::Ptr{Cint}
    body_weldid::Ptr{Cint}
    body_mocapid::Ptr{Cint}
    body_jntnum::Ptr{Cint}
    body_jntadr::Ptr{Cint}
    body_dofnum::Ptr{Cint}
    body_dofadr::Ptr{Cint}
    body_geomnum::Ptr{Cint}
    body_geomadr::Ptr{Cint}
    body_simple::Ptr{mjtByte}
    body_sameframe::Ptr{mjtByte}
    body_pos::Ptr{mjtNum}
    body_quat::Ptr{mjtNum}
    body_ipos::Ptr{mjtNum}
    body_iquat::Ptr{mjtNum}
    body_mass::Ptr{mjtNum}
    body_subtreemass::Ptr{mjtNum}
    body_inertia::Ptr{mjtNum}
    body_invweight0::Ptr{mjtNum}
    body_gravcomp::Ptr{mjtNum}
    body_user::Ptr{mjtNum}
    body_plugin::Ptr{Cint}
    body_bvhadr::Ptr{Cint}
    body_bvhnum::Ptr{Cint}
    bvh_depth::Ptr{Cint}
    bvh_child::Ptr{Cint}
    bvh_geomid::Ptr{Cint}
    bvh_aabb::Ptr{mjtNum}
    jnt_type::Ptr{Cint}
    jnt_qposadr::Ptr{Cint}
    jnt_dofadr::Ptr{Cint}
    jnt_bodyid::Ptr{Cint}
    jnt_group::Ptr{Cint}
    jnt_limited::Ptr{mjtByte}
    jnt_actfrclimited::Ptr{mjtByte}
    jnt_solref::Ptr{mjtNum}
    jnt_solimp::Ptr{mjtNum}
    jnt_pos::Ptr{mjtNum}
    jnt_axis::Ptr{mjtNum}
    jnt_stiffness::Ptr{mjtNum}
    jnt_range::Ptr{mjtNum}
    jnt_actfrcrange::Ptr{mjtNum}
    jnt_margin::Ptr{mjtNum}
    jnt_user::Ptr{mjtNum}
    dof_bodyid::Ptr{Cint}
    dof_jntid::Ptr{Cint}
    dof_parentid::Ptr{Cint}
    dof_Madr::Ptr{Cint}
    dof_simplenum::Ptr{Cint}
    dof_solref::Ptr{mjtNum}
    dof_solimp::Ptr{mjtNum}
    dof_frictionloss::Ptr{mjtNum}
    dof_armature::Ptr{mjtNum}
    dof_damping::Ptr{mjtNum}
    dof_invweight0::Ptr{mjtNum}
    dof_M0::Ptr{mjtNum}
    geom_type::Ptr{Cint}
    geom_contype::Ptr{Cint}
    geom_conaffinity::Ptr{Cint}
    geom_condim::Ptr{Cint}
    geom_bodyid::Ptr{Cint}
    geom_dataid::Ptr{Cint}
    geom_matid::Ptr{Cint}
    geom_group::Ptr{Cint}
    geom_priority::Ptr{Cint}
    geom_sameframe::Ptr{mjtByte}
    geom_solmix::Ptr{mjtNum}
    geom_solref::Ptr{mjtNum}
    geom_solimp::Ptr{mjtNum}
    geom_size::Ptr{mjtNum}
    geom_aabb::Ptr{mjtNum}
    geom_rbound::Ptr{mjtNum}
    geom_pos::Ptr{mjtNum}
    geom_quat::Ptr{mjtNum}
    geom_friction::Ptr{mjtNum}
    geom_margin::Ptr{mjtNum}
    geom_gap::Ptr{mjtNum}
    geom_fluid::Ptr{mjtNum}
    geom_user::Ptr{mjtNum}
    geom_rgba::Ptr{Cfloat}
    site_type::Ptr{Cint}
    site_bodyid::Ptr{Cint}
    site_matid::Ptr{Cint}
    site_group::Ptr{Cint}
    site_sameframe::Ptr{mjtByte}
    site_size::Ptr{mjtNum}
    site_pos::Ptr{mjtNum}
    site_quat::Ptr{mjtNum}
    site_user::Ptr{mjtNum}
    site_rgba::Ptr{Cfloat}
    cam_mode::Ptr{Cint}
    cam_bodyid::Ptr{Cint}
    cam_targetbodyid::Ptr{Cint}
    cam_pos::Ptr{mjtNum}
    cam_quat::Ptr{mjtNum}
    cam_poscom0::Ptr{mjtNum}
    cam_pos0::Ptr{mjtNum}
    cam_mat0::Ptr{mjtNum}
    cam_fovy::Ptr{mjtNum}
    cam_ipd::Ptr{mjtNum}
    cam_user::Ptr{mjtNum}
    light_mode::Ptr{Cint}
    light_bodyid::Ptr{Cint}
    light_targetbodyid::Ptr{Cint}
    light_directional::Ptr{mjtByte}
    light_castshadow::Ptr{mjtByte}
    light_active::Ptr{mjtByte}
    light_pos::Ptr{mjtNum}
    light_dir::Ptr{mjtNum}
    light_poscom0::Ptr{mjtNum}
    light_pos0::Ptr{mjtNum}
    light_dir0::Ptr{mjtNum}
    light_attenuation::Ptr{Cfloat}
    light_cutoff::Ptr{Cfloat}
    light_exponent::Ptr{Cfloat}
    light_ambient::Ptr{Cfloat}
    light_diffuse::Ptr{Cfloat}
    light_specular::Ptr{Cfloat}
    mesh_vertadr::Ptr{Cint}
    mesh_vertnum::Ptr{Cint}
    mesh_faceadr::Ptr{Cint}
    mesh_facenum::Ptr{Cint}
    mesh_bvhadr::Ptr{Cint}
    mesh_bvhnum::Ptr{Cint}
    mesh_normaladr::Ptr{Cint}
    mesh_normalnum::Ptr{Cint}
    mesh_texcoordadr::Ptr{Cint}
    mesh_texcoordnum::Ptr{Cint}
    mesh_graphadr::Ptr{Cint}
    mesh_vert::Ptr{Cfloat}
    mesh_normal::Ptr{Cfloat}
    mesh_texcoord::Ptr{Cfloat}
    mesh_face::Ptr{Cint}
    mesh_facenormal::Ptr{Cint}
    mesh_facetexcoord::Ptr{Cint}
    mesh_graph::Ptr{Cint}
    skin_matid::Ptr{Cint}
    skin_group::Ptr{Cint}
    skin_rgba::Ptr{Cfloat}
    skin_inflate::Ptr{Cfloat}
    skin_vertadr::Ptr{Cint}
    skin_vertnum::Ptr{Cint}
    skin_texcoordadr::Ptr{Cint}
    skin_faceadr::Ptr{Cint}
    skin_facenum::Ptr{Cint}
    skin_boneadr::Ptr{Cint}
    skin_bonenum::Ptr{Cint}
    skin_vert::Ptr{Cfloat}
    skin_texcoord::Ptr{Cfloat}
    skin_face::Ptr{Cint}
    skin_bonevertadr::Ptr{Cint}
    skin_bonevertnum::Ptr{Cint}
    skin_bonebindpos::Ptr{Cfloat}
    skin_bonebindquat::Ptr{Cfloat}
    skin_bonebodyid::Ptr{Cint}
    skin_bonevertid::Ptr{Cint}
    skin_bonevertweight::Ptr{Cfloat}
    hfield_size::Ptr{mjtNum}
    hfield_nrow::Ptr{Cint}
    hfield_ncol::Ptr{Cint}
    hfield_adr::Ptr{Cint}
    hfield_data::Ptr{Cfloat}
    tex_type::Ptr{Cint}
    tex_height::Ptr{Cint}
    tex_width::Ptr{Cint}
    tex_adr::Ptr{Cint}
    tex_rgb::Ptr{mjtByte}
    mat_texid::Ptr{Cint}
    mat_texuniform::Ptr{mjtByte}
    mat_texrepeat::Ptr{Cfloat}
    mat_emission::Ptr{Cfloat}
    mat_specular::Ptr{Cfloat}
    mat_shininess::Ptr{Cfloat}
    mat_reflectance::Ptr{Cfloat}
    mat_rgba::Ptr{Cfloat}
    pair_dim::Ptr{Cint}
    pair_geom1::Ptr{Cint}
    pair_geom2::Ptr{Cint}
    pair_signature::Ptr{Cint}
    pair_solref::Ptr{mjtNum}
    pair_solreffriction::Ptr{mjtNum}
    pair_solimp::Ptr{mjtNum}
    pair_margin::Ptr{mjtNum}
    pair_gap::Ptr{mjtNum}
    pair_friction::Ptr{mjtNum}
    exclude_signature::Ptr{Cint}
    eq_type::Ptr{Cint}
    eq_obj1id::Ptr{Cint}
    eq_obj2id::Ptr{Cint}
    eq_active::Ptr{mjtByte}
    eq_solref::Ptr{mjtNum}
    eq_solimp::Ptr{mjtNum}
    eq_data::Ptr{mjtNum}
    tendon_adr::Ptr{Cint}
    tendon_num::Ptr{Cint}
    tendon_matid::Ptr{Cint}
    tendon_group::Ptr{Cint}
    tendon_limited::Ptr{mjtByte}
    tendon_width::Ptr{mjtNum}
    tendon_solref_lim::Ptr{mjtNum}
    tendon_solimp_lim::Ptr{mjtNum}
    tendon_solref_fri::Ptr{mjtNum}
    tendon_solimp_fri::Ptr{mjtNum}
    tendon_range::Ptr{mjtNum}
    tendon_margin::Ptr{mjtNum}
    tendon_stiffness::Ptr{mjtNum}
    tendon_damping::Ptr{mjtNum}
    tendon_frictionloss::Ptr{mjtNum}
    tendon_lengthspring::Ptr{mjtNum}
    tendon_length0::Ptr{mjtNum}
    tendon_invweight0::Ptr{mjtNum}
    tendon_user::Ptr{mjtNum}
    tendon_rgba::Ptr{Cfloat}
    wrap_type::Ptr{Cint}
    wrap_objid::Ptr{Cint}
    wrap_prm::Ptr{mjtNum}
    actuator_trntype::Ptr{Cint}
    actuator_dyntype::Ptr{Cint}
    actuator_gaintype::Ptr{Cint}
    actuator_biastype::Ptr{Cint}
    actuator_trnid::Ptr{Cint}
    actuator_actadr::Ptr{Cint}
    actuator_actnum::Ptr{Cint}
    actuator_group::Ptr{Cint}
    actuator_ctrllimited::Ptr{mjtByte}
    actuator_forcelimited::Ptr{mjtByte}
    actuator_actlimited::Ptr{mjtByte}
    actuator_dynprm::Ptr{mjtNum}
    actuator_gainprm::Ptr{mjtNum}
    actuator_biasprm::Ptr{mjtNum}
    actuator_ctrlrange::Ptr{mjtNum}
    actuator_forcerange::Ptr{mjtNum}
    actuator_actrange::Ptr{mjtNum}
    actuator_gear::Ptr{mjtNum}
    actuator_cranklength::Ptr{mjtNum}
    actuator_acc0::Ptr{mjtNum}
    actuator_length0::Ptr{mjtNum}
    actuator_lengthrange::Ptr{mjtNum}
    actuator_user::Ptr{mjtNum}
    actuator_plugin::Ptr{Cint}
    sensor_type::Ptr{Cint}
    sensor_datatype::Ptr{Cint}
    sensor_needstage::Ptr{Cint}
    sensor_objtype::Ptr{Cint}
    sensor_objid::Ptr{Cint}
    sensor_reftype::Ptr{Cint}
    sensor_refid::Ptr{Cint}
    sensor_dim::Ptr{Cint}
    sensor_adr::Ptr{Cint}
    sensor_cutoff::Ptr{mjtNum}
    sensor_noise::Ptr{mjtNum}
    sensor_user::Ptr{mjtNum}
    sensor_plugin::Ptr{Cint}
    plugin::Ptr{Cint}
    plugin_stateadr::Ptr{Cint}
    plugin_statenum::Ptr{Cint}
    plugin_attr::Ptr{Cchar}
    plugin_attradr::Ptr{Cint}
    numeric_adr::Ptr{Cint}
    numeric_size::Ptr{Cint}
    numeric_data::Ptr{mjtNum}
    text_adr::Ptr{Cint}
    text_size::Ptr{Cint}
    text_data::Ptr{Cchar}
    tuple_adr::Ptr{Cint}
    tuple_size::Ptr{Cint}
    tuple_objtype::Ptr{Cint}
    tuple_objid::Ptr{Cint}
    tuple_objprm::Ptr{mjtNum}
    key_time::Ptr{mjtNum}
    key_qpos::Ptr{mjtNum}
    key_qvel::Ptr{mjtNum}
    key_act::Ptr{mjtNum}
    key_mpos::Ptr{mjtNum}
    key_mquat::Ptr{mjtNum}
    key_ctrl::Ptr{mjtNum}
    name_bodyadr::Ptr{Cint}
    name_jntadr::Ptr{Cint}
    name_geomadr::Ptr{Cint}
    name_siteadr::Ptr{Cint}
    name_camadr::Ptr{Cint}
    name_lightadr::Ptr{Cint}
    name_meshadr::Ptr{Cint}
    name_skinadr::Ptr{Cint}
    name_hfieldadr::Ptr{Cint}
    name_texadr::Ptr{Cint}
    name_matadr::Ptr{Cint}
    name_pairadr::Ptr{Cint}
    name_excludeadr::Ptr{Cint}
    name_eqadr::Ptr{Cint}
    name_tendonadr::Ptr{Cint}
    name_actuatoradr::Ptr{Cint}
    name_sensoradr::Ptr{Cint}
    name_numericadr::Ptr{Cint}
    name_textadr::Ptr{Cint}
    name_tupleadr::Ptr{Cint}
    name_keyadr::Ptr{Cint}
    name_pluginadr::Ptr{Cint}
    names::Ptr{Cchar}
    names_map::Ptr{Cint}
end
const mjModel = mjModel_
struct mjpResourceProvider_
    prefix::Ptr{Cchar}
    open::mjfOpenResource
    read::mjfReadResource
    close::mjfCloseResource
    getdir::mjfGetResourceDir
    data::Ptr{Cvoid}
end
const mjpResourceProvider = mjpResourceProvider_
const mjtPluginCapabilityBit = mjtPluginCapabilityBit_
struct mjpPlugin_
    name::Ptr{Cchar}
    nattribute::Cint
    attributes::Ptr{Ptr{Cchar}}
    capabilityflags::Cint
    needstage::Cint
    nstate::Ptr{Cvoid}
    nsensordata::Ptr{Cvoid}
    init::Ptr{Cvoid}
    destroy::Ptr{Cvoid}
    copy::Ptr{Cvoid}
    reset::Ptr{Cvoid}
    compute::Ptr{Cvoid}
    advance::Ptr{Cvoid}
    visualize::Ptr{Cvoid}
end
const mjpPlugin = mjpPlugin_
const mjtGridPos = mjtGridPos_
const mjtFramebuffer = mjtFramebuffer_
const mjtFontScale = mjtFontScale_
const mjtFont = mjtFont_
struct mjrRect_
    left::Cint
    bottom::Cint
    width::Cint
    height::Cint
end
const mjrRect = mjrRect_
struct mjrContext_
    lineWidth::Cfloat
    shadowClip::Cfloat
    shadowScale::Cfloat
    fogStart::Cfloat
    fogEnd::Cfloat
    fogRGBA::NTuple{4,Cfloat}
    shadowSize::Cint
    offWidth::Cint
    offHeight::Cint
    offSamples::Cint
    fontScale::Cint
    auxWidth::NTuple{10,Cint}
    auxHeight::NTuple{10,Cint}
    auxSamples::NTuple{10,Cint}
    offFBO::Cuint
    offFBO_r::Cuint
    offColor::Cuint
    offColor_r::Cuint
    offDepthStencil::Cuint
    offDepthStencil_r::Cuint
    shadowFBO::Cuint
    shadowTex::Cuint
    auxFBO::NTuple{10,Cuint}
    auxFBO_r::NTuple{10,Cuint}
    auxColor::NTuple{10,Cuint}
    auxColor_r::NTuple{10,Cuint}
    ntexture::Cint
    textureType::NTuple{100,Cint}
    texture::NTuple{100,Cuint}
    basePlane::Cuint
    baseMesh::Cuint
    baseHField::Cuint
    baseBuiltin::Cuint
    baseFontNormal::Cuint
    baseFontShadow::Cuint
    baseFontBig::Cuint
    rangePlane::Cint
    rangeMesh::Cint
    rangeHField::Cint
    rangeBuiltin::Cint
    rangeFont::Cint
    nskin::Cint
    skinvertVBO::Ptr{Cuint}
    skinnormalVBO::Ptr{Cuint}
    skintexcoordVBO::Ptr{Cuint}
    skinfaceVBO::Ptr{Cuint}
    charWidth::NTuple{127,Cint}
    charWidthBig::NTuple{127,Cint}
    charHeight::Cint
    charHeightBig::Cint
    glInitialized::Cint
    windowAvailable::Cint
    windowSamples::Cint
    windowStereo::Cint
    windowDoublebuffer::Cint
    currentBuffer::Cint
    readPixelFormat::Cint
end
const mjrContext = mjrContext_
const mjtButton = mjtButton_
const mjtEvent = mjtEvent_
const mjtItem = mjtItem_
struct mjuiState_
    nrect::Cint
    rect::NTuple{25,mjrRect}
    userdata::Ptr{Cvoid}
    type::Cint
    left::Cint
    right::Cint
    middle::Cint
    doubleclick::Cint
    button::Cint
    buttontime::Cdouble
    x::Cdouble
    y::Cdouble
    dx::Cdouble
    dy::Cdouble
    sx::Cdouble
    sy::Cdouble
    control::Cint
    shift::Cint
    alt::Cint
    key::Cint
    keytime::Cdouble
    mouserect::Cint
    dragrect::Cint
    dragbutton::Cint
    dropcount::Cint
    droppaths::Ptr{Ptr{Cchar}}
end
const mjuiState = mjuiState_
struct mjuiThemeSpacing_
    total::Cint
    scroll::Cint
    label::Cint
    section::Cint
    itemside::Cint
    itemmid::Cint
    itemver::Cint
    texthor::Cint
    textver::Cint
    linescroll::Cint
    samples::Cint
end
const mjuiThemeSpacing = mjuiThemeSpacing_
struct mjuiThemeColor_
    master::NTuple{3,Cfloat}
    thumb::NTuple{3,Cfloat}
    secttitle::NTuple{3,Cfloat}
    sectfont::NTuple{3,Cfloat}
    sectsymbol::NTuple{3,Cfloat}
    sectpane::NTuple{3,Cfloat}
    shortcut::NTuple{3,Cfloat}
    fontactive::NTuple{3,Cfloat}
    fontinactive::NTuple{3,Cfloat}
    decorinactive::NTuple{3,Cfloat}
    decorinactive2::NTuple{3,Cfloat}
    button::NTuple{3,Cfloat}
    check::NTuple{3,Cfloat}
    radio::NTuple{3,Cfloat}
    select::NTuple{3,Cfloat}
    select2::NTuple{3,Cfloat}
    slider::NTuple{3,Cfloat}
    slider2::NTuple{3,Cfloat}
    edit::NTuple{3,Cfloat}
    edit2::NTuple{3,Cfloat}
    cursor::NTuple{3,Cfloat}
end
const mjuiThemeColor = mjuiThemeColor_
struct mjuiItemSingle_
    modifier::Cint
    shortcut::Cint
end
struct mjuiItemMulti_
    nelem::Cint
    name::NTuple{35,NTuple{40,Cchar}}
end
struct mjuiItemSlider_
    range::NTuple{2,Cdouble}
    divisions::Cdouble
end
struct mjuiItemEdit_
    nelem::Cint
    range::NTuple{7,NTuple{2,Cdouble}}
end
struct mjuiItem_
    data::NTuple{1488,UInt8}
end
const mjuiItem = mjuiItem_
struct mjuiSection_
    name::NTuple{40,Cchar}
    state::Cint
    modifier::Cint
    shortcut::Cint
    nitem::Cint
    item::NTuple{100,mjuiItem}
    rtitle::mjrRect
    rcontent::mjrRect
end
const mjuiSection = mjuiSection_
struct mjUI_
    spacing::mjuiThemeSpacing
    color::mjuiThemeColor
    predicate::mjfItemEnable
    userdata::Ptr{Cvoid}
    rectid::Cint
    auxid::Cint
    radiocol::Cint
    width::Cint
    height::Cint
    maxheight::Cint
    scroll::Cint
    mousesect::Cint
    mouseitem::Cint
    mousehelp::Cint
    editsect::Cint
    edititem::Cint
    editcursor::Cint
    editscroll::Cint
    edittext::NTuple{300,Cchar}
    editchanged::Ptr{mjuiItem}
    nsect::Cint
    sect::NTuple{10,mjuiSection}
end
const mjUI = mjUI_
struct mjuiDef_
    type::Cint
    name::NTuple{40,Cchar}
    state::Cint
    pdata::Ptr{Cvoid}
    other::NTuple{300,Cchar}
end
const mjuiDef = mjuiDef_
const mjtCatBit = mjtCatBit_
const mjtMouse = mjtMouse_
const mjtPertBit = mjtPertBit_
const mjtCamera = mjtCamera_
const mjtLabel = mjtLabel_
const mjtFrame = mjtFrame_
const mjtVisFlag = mjtVisFlag_
const mjtRndFlag = mjtRndFlag_
const mjtStereo = mjtStereo_
struct mjvPerturb_
    select::Cint
    skinselect::Cint
    active::Cint
    active2::Cint
    refpos::NTuple{3,mjtNum}
    refquat::NTuple{4,mjtNum}
    refselpos::NTuple{3,mjtNum}
    localpos::NTuple{3,mjtNum}
    localmass::mjtNum
    scale::mjtNum
end
const mjvPerturb = mjvPerturb_
struct mjvCamera_
    type::Cint
    fixedcamid::Cint
    trackbodyid::Cint
    lookat::NTuple{3,mjtNum}
    distance::mjtNum
    azimuth::mjtNum
    elevation::mjtNum
end
const mjvCamera = mjvCamera_
struct mjvGLCamera_
    pos::NTuple{3,Cfloat}
    forward::NTuple{3,Cfloat}
    up::NTuple{3,Cfloat}
    frustum_center::Cfloat
    frustum_bottom::Cfloat
    frustum_top::Cfloat
    frustum_near::Cfloat
    frustum_far::Cfloat
end
const mjvGLCamera = mjvGLCamera_
struct mjvGeom_
    type::Cint
    dataid::Cint
    objtype::Cint
    objid::Cint
    category::Cint
    texid::Cint
    texuniform::Cint
    texcoord::Cint
    segid::Cint
    texrepeat::NTuple{2,Cfloat}
    size::NTuple{3,Cfloat}
    pos::NTuple{3,Cfloat}
    mat::NTuple{9,Cfloat}
    rgba::NTuple{4,Cfloat}
    emission::Cfloat
    specular::Cfloat
    shininess::Cfloat
    reflectance::Cfloat
    label::NTuple{100,Cchar}
    camdist::Cfloat
    modelrbound::Cfloat
    transparent::mjtByte
end
const mjvGeom = mjvGeom_
struct mjvLight_
    pos::NTuple{3,Cfloat}
    dir::NTuple{3,Cfloat}
    attenuation::NTuple{3,Cfloat}
    cutoff::Cfloat
    exponent::Cfloat
    ambient::NTuple{3,Cfloat}
    diffuse::NTuple{3,Cfloat}
    specular::NTuple{3,Cfloat}
    headlight::mjtByte
    directional::mjtByte
    castshadow::mjtByte
end
const mjvLight = mjvLight_
struct mjvOption_
    label::Cint
    frame::Cint
    geomgroup::NTuple{6,mjtByte}
    sitegroup::NTuple{6,mjtByte}
    jointgroup::NTuple{6,mjtByte}
    tendongroup::NTuple{6,mjtByte}
    actuatorgroup::NTuple{6,mjtByte}
    skingroup::NTuple{6,mjtByte}
    flags::NTuple{25,mjtByte}
    bvh_depth::Cint
end
const mjvOption = mjvOption_
struct mjvScene_
    maxgeom::Cint
    ngeom::Cint
    geoms::Ptr{mjvGeom}
    geomorder::Ptr{Cint}
    nskin::Cint
    skinfacenum::Ptr{Cint}
    skinvertadr::Ptr{Cint}
    skinvertnum::Ptr{Cint}
    skinvert::Ptr{Cfloat}
    skinnormal::Ptr{Cfloat}
    nlight::Cint
    lights::NTuple{100,mjvLight}
    camera::NTuple{2,mjvGLCamera}
    enabletransform::mjtByte
    translate::NTuple{3,Cfloat}
    rotate::NTuple{4,Cfloat}
    scale::Cfloat
    stereo::Cint
    flags::NTuple{10,mjtByte}
    framewidth::Cint
    framergb::NTuple{3,Cfloat}
end
const mjvScene = mjvScene_
struct mjvFigure_
    flg_legend::Cint
    flg_ticklabel::NTuple{2,Cint}
    flg_extend::Cint
    flg_barplot::Cint
    flg_selection::Cint
    flg_symmetric::Cint
    linewidth::Cfloat
    gridwidth::Cfloat
    gridsize::NTuple{2,Cint}
    gridrgb::NTuple{3,Cfloat}
    figurergba::NTuple{4,Cfloat}
    panergba::NTuple{4,Cfloat}
    legendrgba::NTuple{4,Cfloat}
    textrgb::NTuple{3,Cfloat}
    linergb::NTuple{100,NTuple{3,Cfloat}}
    range::NTuple{2,NTuple{2,Cfloat}}
    xformat::NTuple{20,Cchar}
    yformat::NTuple{20,Cchar}
    minwidth::NTuple{20,Cchar}
    title::NTuple{1000,Cchar}
    xlabel::NTuple{100,Cchar}
    linename::NTuple{100,NTuple{100,Cchar}}
    legendoffset::Cint
    subplot::Cint
    highlight::NTuple{2,Cint}
    highlightid::Cint
    selection::Cfloat
    linepnt::NTuple{100,Cint}
    linedata::NTuple{100,NTuple{2000,Cfloat}}
    xaxispixel::NTuple{2,Cint}
    yaxispixel::NTuple{2,Cint}
    xaxisdata::NTuple{2,Cfloat}
    yaxisdata::NTuple{2,Cfloat}
end
const mjvFigure = mjvFigure_
struct var"##Ctag#320"
    nu::Cint
    na::Cint
    nbody::Cint
    nbvh::Cint
    njnt::Cint
    ngeom::Cint
    nsite::Cint
    ncam::Cint
    nlight::Cint
    nmesh::Cint
    nskin::Cint
    nskinvert::Cint
    nskinface::Cint
    nskinbone::Cint
    nskinbonevert::Cint
    nmat::Cint
    neq::Cint
    ntendon::Cint
    nwrap::Cint
    nsensor::Cint
    nnames::Cint
    nsensordata::Cint
    opt::mjOption
    vis::mjVisual
    stat::mjStatistic
    body_parentid::Ptr{Cint}
    body_rootid::Ptr{Cint}
    body_weldid::Ptr{Cint}
    body_mocapid::Ptr{Cint}
    body_jntnum::Ptr{Cint}
    body_jntadr::Ptr{Cint}
    body_geomnum::Ptr{Cint}
    body_geomadr::Ptr{Cint}
    body_iquat::Ptr{mjtNum}
    body_mass::Ptr{mjtNum}
    body_inertia::Ptr{mjtNum}
    body_bvhadr::Ptr{Cint}
    body_bvhnum::Ptr{Cint}
    bvh_depth::Ptr{Cint}
    bvh_child::Ptr{Cint}
    bvh_geomid::Ptr{Cint}
    bvh_aabb::Ptr{mjtNum}
    jnt_type::Ptr{Cint}
    jnt_bodyid::Ptr{Cint}
    jnt_group::Ptr{Cint}
    geom_type::Ptr{Cint}
    geom_bodyid::Ptr{Cint}
    geom_dataid::Ptr{Cint}
    geom_matid::Ptr{Cint}
    geom_group::Ptr{Cint}
    geom_size::Ptr{mjtNum}
    geom_aabb::Ptr{mjtNum}
    geom_rbound::Ptr{mjtNum}
    geom_rgba::Ptr{Cfloat}
    site_type::Ptr{Cint}
    site_bodyid::Ptr{Cint}
    site_matid::Ptr{Cint}
    site_group::Ptr{Cint}
    site_size::Ptr{mjtNum}
    site_rgba::Ptr{Cfloat}
    cam_fovy::Ptr{mjtNum}
    cam_ipd::Ptr{mjtNum}
    light_directional::Ptr{mjtByte}
    light_castshadow::Ptr{mjtByte}
    light_active::Ptr{mjtByte}
    light_attenuation::Ptr{Cfloat}
    light_cutoff::Ptr{Cfloat}
    light_exponent::Ptr{Cfloat}
    light_ambient::Ptr{Cfloat}
    light_diffuse::Ptr{Cfloat}
    light_specular::Ptr{Cfloat}
    mesh_texcoordadr::Ptr{Cint}
    mesh_graphadr::Ptr{Cint}
    skin_matid::Ptr{Cint}
    skin_group::Ptr{Cint}
    skin_rgba::Ptr{Cfloat}
    skin_inflate::Ptr{Cfloat}
    skin_vertadr::Ptr{Cint}
    skin_vertnum::Ptr{Cint}
    skin_texcoordadr::Ptr{Cint}
    skin_faceadr::Ptr{Cint}
    skin_facenum::Ptr{Cint}
    skin_boneadr::Ptr{Cint}
    skin_bonenum::Ptr{Cint}
    skin_vert::Ptr{Cfloat}
    skin_face::Ptr{Cint}
    skin_bonevertadr::Ptr{Cint}
    skin_bonevertnum::Ptr{Cint}
    skin_bonebindpos::Ptr{Cfloat}
    skin_bonebindquat::Ptr{Cfloat}
    skin_bonebodyid::Ptr{Cint}
    skin_bonevertid::Ptr{Cint}
    skin_bonevertweight::Ptr{Cfloat}
    mat_texid::Ptr{Cint}
    mat_texuniform::Ptr{mjtByte}
    mat_texrepeat::Ptr{Cfloat}
    mat_emission::Ptr{Cfloat}
    mat_specular::Ptr{Cfloat}
    mat_shininess::Ptr{Cfloat}
    mat_reflectance::Ptr{Cfloat}
    mat_rgba::Ptr{Cfloat}
    eq_type::Ptr{Cint}
    eq_obj1id::Ptr{Cint}
    eq_obj2id::Ptr{Cint}
    eq_active::Ptr{mjtByte}
    eq_data::Ptr{mjtNum}
    tendon_num::Ptr{Cint}
    tendon_matid::Ptr{Cint}
    tendon_group::Ptr{Cint}
    tendon_limited::Ptr{mjtByte}
    tendon_width::Ptr{mjtNum}
    tendon_range::Ptr{mjtNum}
    tendon_stiffness::Ptr{mjtNum}
    tendon_damping::Ptr{mjtNum}
    tendon_frictionloss::Ptr{mjtNum}
    tendon_lengthspring::Ptr{mjtNum}
    tendon_rgba::Ptr{Cfloat}
    actuator_trntype::Ptr{Cint}
    actuator_dyntype::Ptr{Cint}
    actuator_trnid::Ptr{Cint}
    actuator_actadr::Ptr{Cint}
    actuator_actnum::Ptr{Cint}
    actuator_group::Ptr{Cint}
    actuator_ctrllimited::Ptr{mjtByte}
    actuator_actlimited::Ptr{mjtByte}
    actuator_ctrlrange::Ptr{mjtNum}
    actuator_actrange::Ptr{mjtNum}
    actuator_cranklength::Ptr{mjtNum}
    sensor_type::Ptr{Cint}
    sensor_objid::Ptr{Cint}
    sensor_adr::Ptr{Cint}
    name_bodyadr::Ptr{Cint}
    name_jntadr::Ptr{Cint}
    name_geomadr::Ptr{Cint}
    name_siteadr::Ptr{Cint}
    name_camadr::Ptr{Cint}
    name_lightadr::Ptr{Cint}
    name_eqadr::Ptr{Cint}
    name_tendonadr::Ptr{Cint}
    name_actuatoradr::Ptr{Cint}
    names::Ptr{Cchar}
end
struct var"##Ctag#321"
    warning::NTuple{8,mjWarningStat}
    nefc::Cint
    ncon::Cint
    time::mjtNum
    act::Ptr{mjtNum}
    ctrl::Ptr{mjtNum}
    xfrc_applied::Ptr{mjtNum}
    sensordata::Ptr{mjtNum}
    xpos::Ptr{mjtNum}
    xquat::Ptr{mjtNum}
    xmat::Ptr{mjtNum}
    xipos::Ptr{mjtNum}
    ximat::Ptr{mjtNum}
    xanchor::Ptr{mjtNum}
    xaxis::Ptr{mjtNum}
    geom_xpos::Ptr{mjtNum}
    geom_xmat::Ptr{mjtNum}
    site_xpos::Ptr{mjtNum}
    site_xmat::Ptr{mjtNum}
    cam_xpos::Ptr{mjtNum}
    cam_xmat::Ptr{mjtNum}
    light_xpos::Ptr{mjtNum}
    light_xdir::Ptr{mjtNum}
    subtree_com::Ptr{mjtNum}
    ten_wrapadr::Ptr{Cint}
    ten_wrapnum::Ptr{Cint}
    wrap_obj::Ptr{Cint}
    wrap_xpos::Ptr{mjtNum}
    bvh_active::Ptr{mjtByte}
    contact::Ptr{mjContact}
    efc_force::Ptr{mjtNum}
end
struct mjvSceneState_
    data::NTuple{10856,UInt8}
end
const mjvSceneState = mjvSceneState_
